// Code generated by make go_build_register; DO NOT EDIT.
package handlers

import "testing"

func TestHandlers_registerHandlers(t *testing.T) {
	tests := []struct {
		name string
		h    *Handlers
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.h.registerHandlers()
		})
	}
}
