
export enum IPrompts {
  CREATE_API = 0,
  CREATE_API_BACKEND = 1,
  CREATE_TYPE = 2,
  CREATE_GEN_COMPONENT = 3,
  CREATE_APP_COMPONENT = 4,
  DERIVE_INSTRUCTION = 5,
  FILE_EDITOR = 6,
  GUIDED_EDIT = 7,
  SUGGEST_ROLE = 8,
  SUGGEST_SERVICE = 9,
  SUGGEST_TIER = 10,
  SUGGEST_FEATURE = 11,
  CONVERT_PURPOSE = 12,
}
