#!/bin/bash

psql -v ON_ERROR_STOP=1 <<-EOSQL

  CREATE USER $PG_WORKER WITH PASSWORD '$PG_WORKER_PASS';
  ALTER ROLE $PG_WORKER VALID UNTIL 'infinity';

  CREATE DATABASE keycloak;

  GRANT ALL ON DATABASE keycloak TO $PG_WORKER;
  ALTER DATABASE keycloak OWNER TO $PG_WORKER;

  CREATE DATABASE $PG_DB;

  GRANT ALL ON DATABASE $PG_DB TO $PG_WORKER;
  ALTER DATABASE $PG_DB OWNER TO $PG_WORKER;

EOSQL
