CREATE SCHEMA dbfunc_schema;
CREATE SCHEMA dbtable_schema;
CREATE SCHEMA dbview_schema;

GRANT USAGE ON SCHEMA dbfunc_schema TO $PG_WORKER;
GRANT USAGE ON SCHEMA dbtable_schema TO $PG_WORKER;
GRANT USAGE ON SCHEMA dbview_schema TO $PG_WORKER;

ALTER DEFAULT PRIVILEGES IN SCHEMA dbfunc_schema GRANT EXECUTE ON FUNCTIONS TO $PG_WORKER;
ALTER DEFAULT PRIVILEGES IN SCHEMA dbtable_schema GRANT ALL ON TABLES TO $PG_WORKER;
ALTER DEFAULT PRIVILEGES IN SCHEMA dbview_schema GRANT ALL ON TABLES TO $PG_WORKER;
