DROP DATABASE IF EXISTS $PG_DB;
DROP DATABASE IF EXISTS keycloak;
DROP USER IF EXISTS $PG_WORKER;

CREATE USER $PG_WORKER WITH PASSWORD '$PG_WORKER_PASS';
ALTER ROLE $PG_WORKER VALID UNTIL 'infinity';

CREATE DATABASE keycloak;

GRANT ALL ON DATABASE keycloak TO $PG_WORKER;
ALTER DATABASE keycloak OWNER TO $PG_WORKER;

CREATE DATABASE $PG_DB;

ALTER DATABASE $PG_DB SET intervalstyle = 'iso_8601';

GRANT ALL ON DATABASE $PG_DB TO $PG_WORKER;

